# Generated by Django 4.2.5 on 2023-10-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logcutting_sawnlog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SawnLog",
            fields=[
                ("log_id", models.CharField(max_length=100)),
                ("jumlah_potong", models.CharField(max_length=100)),
                (
                    "sawn_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("sawn_length", models.CharField(max_length=100)),
                ("sawn_grade", models.CharField(max_length=100)),
                ("diameter_1", models.CharField(max_length=100)),
                ("diameter_2", models.CharField(max_length=100)),
                ("average_diameter", models.CharField(max_length=100)),
                ("volume", models.CharField(max_length=100)),
            ],
            options={
                "db_table": 'log_cutting"."sawn_log_test',
            },
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
