# Generated by Django 4.2.5 on 2023-10-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logcutting_loglist", "0002_loglist_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partai",
            fields=[
                (
                    "partai_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": 'log_cutting"."partai',
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "species_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("species_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": 'log_cutting"."species_log',
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "supplier_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("supplier_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": 'log_cutting"."supplier_logs',
            },
        ),
        migrations.RemoveField(
            model_name="loglist",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="loglist",
            name="average_diameter",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loglist",
            name="diameter_1",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="loglist",
            name="diameter_2",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="loglist",
            name="log_length",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loglist",
            name="volume_bruto",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loglist",
            name="volume_netto",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loglist",
            name="volume_trimming",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
